### ISSUE TITLE
No Scrollbar

### ISSUE THREAD

**Issue by benrob0329** [Lootyhoof/darkmoon#1]
No scrollbar is shown on PM 27.7.0 (DarkMoon downloaded from addons.palemoon.org)

**Comment by Lootyhoof** [comment]
What OS are you using? Have you tried with other extensions disabled?

**Comment by benrob0329** [comment]
Debian Linux 9.3, yes.

**Comment by Lootyhoof** [comment]
Sorry for the delay, but this should be fixed as of v2.0.0. Are you able to confirm?
