### ISSUE TITLE
Checkboxes of Wiping History are gone

### ISSUE THREAD

**Issue by RoestVrijStaal** [Lootyhoof/darkmoon#2]
See attached screenshot

![screenshot_20180523_190229](https://user-images.githubusercontent.com/6899548/40439760-77d7f788-5eab-11e8-8778-5cb32df1b206.png)

You can reproduce it by pressing Ctrl+Shift+Del on Pale Moon 27.9.2 with Dark Moon 2.0.0 

Expanding the window doesn't help.

**Comment by Lootyhoof** [comment]
Thanks for the report! v2.0.1, which I've just released, should have the fix for this.
