### ISSUE TITLE
active tab not clear

### ISSUE THREAD

**Issue by HarkTu** [Lootyhoof/darkmoon#5]
active tab and passive tabs colors are very close, needs effort to find the active tab. could you make active tab color lighter please.tnx
![darkmoon](https://user-images.githubusercontent.com/46054251/66713678-4fca4e80-edb6-11e9-951f-92f0a92d9efe.jpg)

**Comment by Lootyhoof** [comment]
During the initial few versions of this theme several adjustments were already made to this effect based on user feedback, such that the current situation is a sweet spot with most people. I've no plans to change this. However, you could use something like the below, as a style in [Stylem](https://addons.palemoon.org/addon/stylem/):

````
.tabbrowser-tab[selected]:not(:-moz-lwtheme) {
  /* Change the `background-color` value below to anything
   * else to change the color. This could be shorthand
   * (e.g. "red", "blue" etc), RGB(A), or hexidecimal. 
   * The "!important;" must remain at the end. */
  background-color: rgb(255,255,255,.4) !important;
  background-image: none !important;
}
````
